#!/bin/env bash
# Copy files from client to server with strict host key disabled

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"else
    scp -i "$4" -o StrictKeyChecking=no "$1" "$3"@"$2":~/
fi
