#!/usr/bin/env bash
# Install and configure nginx on the server

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
