#!/usr/bin/env bash
#$URI/redirect_me takes redirects to youtube URI

sudo apt-get upgrade -y
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
new_string="\\\\tlocation /redirect_me {\n\t\treturn 301 https:\/\/www\.youtube\.com\/watch\?v=QH2-TGUlwu4;\n\t}"
sudo chmod 777 /etc/nginx/sites-available/default
sed -i "54a $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
