#!/usr/bin/env bash
# sets up a new 404 error page

sdo apt-get upgrade -y
sudo apt-get update -y
sudo apt-get install -y nginx
chown -R "$USER:$USER" /var/www/html
chmod -R 755 /var/www
echo "Hello world" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
new_line="\\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "54a $new_line" /etc/nginx/sites-available/default

mkdir -p /var/www/default
echo "Ceci n'est pas une page" > /var/www/default/404.html
line1="\\\\tlocation = /404.html {\n\t\t root /var/www/default;\n\t}"
sed -i "29i $line1" /etc/nginx/sites-available/default
line2="\\\terror_page 404 /404.html;"
sed -i "32i $line2" /etc/nginx/sites-available/default
service nginx restart
