#!/usr/bin/env bash
# configure the server with new and updated parameters

sudo apt upgrade -y 
sudo apt update -y
sudo apt install nginx -y
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html

q='"'
host=$(hostname)
line1="\\\\tadd_header X-Served-By $q$host$q;"
sed -i "24i $line1" /etc/nginx/sites-available/default

line2="\\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "48i $line2" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
line3="\\\tlocation = /404.html {\n\t\t root /var/www/html;\n\t}"
sed -i "29i $line3" /etc/nginx/sites-available/default
line4="\\\terror_page 404 /404.html;"
sed -i "32i $line4" /etc/nginx/sites-available/default

service nginx restart
