#!/usr/bin/env bash
# create sqldump and compress

if [[ $1 ]]
then
	date=$(date +%d-%m-%Y)
	password=$1
	mysqldump -u root -p"$password" --all-databases > backup.sql
	gzip -c backup.sql > "$date".tar.gz
fi
