#!/usr/bin/env bash
#Prints 'Fizz', 'Buzz' and 'FizzBuzz' for multiples of 3, 5 and both numbers#respectively

for n in {1..100}
do
  if (( n % 3 == 0 && n % 5 == 0 ))
  then
    echo "FizzBuzz" 
  elif (( n % 3 == 0 ))
  then
    echo "Fizz"
  elif (( n % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$n"
  fi
done
