#!/usr/bin/bash
# Configure UFW to forward requests from port 8080 to port 80 locally

sudo ufw allow port 8080
sed -i 's/\(*filter\)/\*nat\n:PREROUTING ACCEPT [0:0]\n-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\nCOMMIT\n\1/g' /etc/ufw/before.rules
sudo systemctl restart ufw
