#!/usr/bin/bash
# Configure UFW to forward requests from port 8080 to port 80 locally
 
conf='\*nat\n:PREROUTING ACCEPT [0:0]\n-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\nCOMMIT'
sed -i 's/\(\*filter\)/$conf/g' test.txt                       
