#!/usr/bin/env bash
#edit the host file in a docker container
#resolve localhost to 127.0.0.2
#resolve facebook.com to 8.8.8.8

cp /etc/hosts ~/host.new
echo "127.0.0.2        localhost" > ~/host.new
echo "8.8.8.8	       facebook.com" >> ~/host.new

cp -f ~host.new /etc/hosts
